// Gateway API - Client to Gateway requests

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: xmtpv4/gateway_api/gateway_api.proto

package gateway_api

import (
	context "context"
	payer_api "github.com/xmtp/xmtp-node-go/pkg/proto/xmtpv4/payer_api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GatewayApi_PublishClientEnvelopes_FullMethodName = "/xmtp.xmtpv4.gateway_api.GatewayApi/PublishClientEnvelopes"
	GatewayApi_GetNodes_FullMethodName               = "/xmtp.xmtpv4.gateway_api.GatewayApi/GetNodes"
)

// GatewayApiClient is the client API for GatewayApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayApiClient interface {
	PublishClientEnvelopes(ctx context.Context, in *payer_api.PublishClientEnvelopesRequest, opts ...grpc.CallOption) (*payer_api.PublishClientEnvelopesResponse, error)
	GetNodes(ctx context.Context, in *payer_api.GetNodesRequest, opts ...grpc.CallOption) (*payer_api.GetNodesResponse, error)
}

type gatewayApiClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayApiClient(cc grpc.ClientConnInterface) GatewayApiClient {
	return &gatewayApiClient{cc}
}

func (c *gatewayApiClient) PublishClientEnvelopes(ctx context.Context, in *payer_api.PublishClientEnvelopesRequest, opts ...grpc.CallOption) (*payer_api.PublishClientEnvelopesResponse, error) {
	out := new(payer_api.PublishClientEnvelopesResponse)
	err := c.cc.Invoke(ctx, GatewayApi_PublishClientEnvelopes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayApiClient) GetNodes(ctx context.Context, in *payer_api.GetNodesRequest, opts ...grpc.CallOption) (*payer_api.GetNodesResponse, error) {
	out := new(payer_api.GetNodesResponse)
	err := c.cc.Invoke(ctx, GatewayApi_GetNodes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayApiServer is the server API for GatewayApi service.
// All implementations must embed UnimplementedGatewayApiServer
// for forward compatibility
type GatewayApiServer interface {
	PublishClientEnvelopes(context.Context, *payer_api.PublishClientEnvelopesRequest) (*payer_api.PublishClientEnvelopesResponse, error)
	GetNodes(context.Context, *payer_api.GetNodesRequest) (*payer_api.GetNodesResponse, error)
	mustEmbedUnimplementedGatewayApiServer()
}

// UnimplementedGatewayApiServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayApiServer struct {
}

func (UnimplementedGatewayApiServer) PublishClientEnvelopes(context.Context, *payer_api.PublishClientEnvelopesRequest) (*payer_api.PublishClientEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishClientEnvelopes not implemented")
}
func (UnimplementedGatewayApiServer) GetNodes(context.Context, *payer_api.GetNodesRequest) (*payer_api.GetNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedGatewayApiServer) mustEmbedUnimplementedGatewayApiServer() {}

// UnsafeGatewayApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayApiServer will
// result in compilation errors.
type UnsafeGatewayApiServer interface {
	mustEmbedUnimplementedGatewayApiServer()
}

func RegisterGatewayApiServer(s grpc.ServiceRegistrar, srv GatewayApiServer) {
	s.RegisterService(&GatewayApi_ServiceDesc, srv)
}

func _GatewayApi_PublishClientEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payer_api.PublishClientEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayApiServer).PublishClientEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayApi_PublishClientEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayApiServer).PublishClientEnvelopes(ctx, req.(*payer_api.PublishClientEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayApi_GetNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payer_api.GetNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayApiServer).GetNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayApi_GetNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayApiServer).GetNodes(ctx, req.(*payer_api.GetNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayApi_ServiceDesc is the grpc.ServiceDesc for GatewayApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmtp.xmtpv4.gateway_api.GatewayApi",
	HandlerType: (*GatewayApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishClientEnvelopes",
			Handler:    _GatewayApi_PublishClientEnvelopes_Handler,
		},
		{
			MethodName: "GetNodes",
			Handler:    _GatewayApi_GetNodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xmtpv4/gateway_api/gateway_api.proto",
}
