// Message API for XMTP V4

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: xmtpv4/message_api/message_api.proto

package message_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ReplicationApi_SubscribeOriginators_FullMethodName  = "/xmtp.xmtpv4.message_api.ReplicationApi/SubscribeOriginators"
	ReplicationApi_SubscribeEnvelopes_FullMethodName    = "/xmtp.xmtpv4.message_api.ReplicationApi/SubscribeEnvelopes"
	ReplicationApi_SubscribeTopics_FullMethodName       = "/xmtp.xmtpv4.message_api.ReplicationApi/SubscribeTopics"
	ReplicationApi_QueryEnvelopes_FullMethodName        = "/xmtp.xmtpv4.message_api.ReplicationApi/QueryEnvelopes"
	ReplicationApi_PublishPayerEnvelopes_FullMethodName = "/xmtp.xmtpv4.message_api.ReplicationApi/PublishPayerEnvelopes"
	ReplicationApi_GetInboxIds_FullMethodName           = "/xmtp.xmtpv4.message_api.ReplicationApi/GetInboxIds"
	ReplicationApi_GetNewestEnvelope_FullMethodName     = "/xmtp.xmtpv4.message_api.ReplicationApi/GetNewestEnvelope"
)

// ReplicationApiClient is the client API for ReplicationApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplicationApiClient interface {
	// Node-to-node originator subscription
	SubscribeOriginators(ctx context.Context, in *SubscribeOriginatorsRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeOriginatorsClient, error)
	// Deprecated: Do not use.
	// Deprecated: use SubscribeOriginators for node queries,
	// QueryApi.SubscribeTopics for client queries
	SubscribeEnvelopes(ctx context.Context, in *SubscribeEnvelopesRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeEnvelopesClient, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	SubscribeTopics(ctx context.Context, in *SubscribeTopicsRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeTopicsClient, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	QueryEnvelopes(ctx context.Context, in *QueryEnvelopesRequest, opts ...grpc.CallOption) (*QueryEnvelopesResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to PublishApi
	PublishPayerEnvelopes(ctx context.Context, in *PublishPayerEnvelopesRequest, opts ...grpc.CallOption) (*PublishPayerEnvelopesResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	GetInboxIds(ctx context.Context, in *GetInboxIdsRequest, opts ...grpc.CallOption) (*GetInboxIdsResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	GetNewestEnvelope(ctx context.Context, in *GetNewestEnvelopeRequest, opts ...grpc.CallOption) (*GetNewestEnvelopeResponse, error)
}

type replicationApiClient struct {
	cc grpc.ClientConnInterface
}

func NewReplicationApiClient(cc grpc.ClientConnInterface) ReplicationApiClient {
	return &replicationApiClient{cc}
}

func (c *replicationApiClient) SubscribeOriginators(ctx context.Context, in *SubscribeOriginatorsRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeOriginatorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReplicationApi_ServiceDesc.Streams[0], ReplicationApi_SubscribeOriginators_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationApiSubscribeOriginatorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReplicationApi_SubscribeOriginatorsClient interface {
	Recv() (*SubscribeOriginatorsResponse, error)
	grpc.ClientStream
}

type replicationApiSubscribeOriginatorsClient struct {
	grpc.ClientStream
}

func (x *replicationApiSubscribeOriginatorsClient) Recv() (*SubscribeOriginatorsResponse, error) {
	m := new(SubscribeOriginatorsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) SubscribeEnvelopes(ctx context.Context, in *SubscribeEnvelopesRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeEnvelopesClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReplicationApi_ServiceDesc.Streams[1], ReplicationApi_SubscribeEnvelopes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationApiSubscribeEnvelopesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReplicationApi_SubscribeEnvelopesClient interface {
	Recv() (*SubscribeEnvelopesResponse, error)
	grpc.ClientStream
}

type replicationApiSubscribeEnvelopesClient struct {
	grpc.ClientStream
}

func (x *replicationApiSubscribeEnvelopesClient) Recv() (*SubscribeEnvelopesResponse, error) {
	m := new(SubscribeEnvelopesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) SubscribeTopics(ctx context.Context, in *SubscribeTopicsRequest, opts ...grpc.CallOption) (ReplicationApi_SubscribeTopicsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReplicationApi_ServiceDesc.Streams[2], ReplicationApi_SubscribeTopics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &replicationApiSubscribeTopicsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ReplicationApi_SubscribeTopicsClient interface {
	Recv() (*SubscribeTopicsResponse, error)
	grpc.ClientStream
}

type replicationApiSubscribeTopicsClient struct {
	grpc.ClientStream
}

func (x *replicationApiSubscribeTopicsClient) Recv() (*SubscribeTopicsResponse, error) {
	m := new(SubscribeTopicsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) QueryEnvelopes(ctx context.Context, in *QueryEnvelopesRequest, opts ...grpc.CallOption) (*QueryEnvelopesResponse, error) {
	out := new(QueryEnvelopesResponse)
	err := c.cc.Invoke(ctx, ReplicationApi_QueryEnvelopes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) PublishPayerEnvelopes(ctx context.Context, in *PublishPayerEnvelopesRequest, opts ...grpc.CallOption) (*PublishPayerEnvelopesResponse, error) {
	out := new(PublishPayerEnvelopesResponse)
	err := c.cc.Invoke(ctx, ReplicationApi_PublishPayerEnvelopes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) GetInboxIds(ctx context.Context, in *GetInboxIdsRequest, opts ...grpc.CallOption) (*GetInboxIdsResponse, error) {
	out := new(GetInboxIdsResponse)
	err := c.cc.Invoke(ctx, ReplicationApi_GetInboxIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *replicationApiClient) GetNewestEnvelope(ctx context.Context, in *GetNewestEnvelopeRequest, opts ...grpc.CallOption) (*GetNewestEnvelopeResponse, error) {
	out := new(GetNewestEnvelopeResponse)
	err := c.cc.Invoke(ctx, ReplicationApi_GetNewestEnvelope_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicationApiServer is the server API for ReplicationApi service.
// All implementations must embed UnimplementedReplicationApiServer
// for forward compatibility
type ReplicationApiServer interface {
	// Node-to-node originator subscription
	SubscribeOriginators(*SubscribeOriginatorsRequest, ReplicationApi_SubscribeOriginatorsServer) error
	// Deprecated: Do not use.
	// Deprecated: use SubscribeOriginators for node queries,
	// QueryApi.SubscribeTopics for client queries
	SubscribeEnvelopes(*SubscribeEnvelopesRequest, ReplicationApi_SubscribeEnvelopesServer) error
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	SubscribeTopics(*SubscribeTopicsRequest, ReplicationApi_SubscribeTopicsServer) error
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	QueryEnvelopes(context.Context, *QueryEnvelopesRequest) (*QueryEnvelopesResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to PublishApi
	PublishPayerEnvelopes(context.Context, *PublishPayerEnvelopesRequest) (*PublishPayerEnvelopesResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	GetInboxIds(context.Context, *GetInboxIdsRequest) (*GetInboxIdsResponse, error)
	// Deprecated: Do not use.
	// Deprecated: moved to QueryApi
	GetNewestEnvelope(context.Context, *GetNewestEnvelopeRequest) (*GetNewestEnvelopeResponse, error)
	mustEmbedUnimplementedReplicationApiServer()
}

// UnimplementedReplicationApiServer must be embedded to have forward compatible implementations.
type UnimplementedReplicationApiServer struct {
}

func (UnimplementedReplicationApiServer) SubscribeOriginators(*SubscribeOriginatorsRequest, ReplicationApi_SubscribeOriginatorsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOriginators not implemented")
}
func (UnimplementedReplicationApiServer) SubscribeEnvelopes(*SubscribeEnvelopesRequest, ReplicationApi_SubscribeEnvelopesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEnvelopes not implemented")
}
func (UnimplementedReplicationApiServer) SubscribeTopics(*SubscribeTopicsRequest, ReplicationApi_SubscribeTopicsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTopics not implemented")
}
func (UnimplementedReplicationApiServer) QueryEnvelopes(context.Context, *QueryEnvelopesRequest) (*QueryEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEnvelopes not implemented")
}
func (UnimplementedReplicationApiServer) PublishPayerEnvelopes(context.Context, *PublishPayerEnvelopesRequest) (*PublishPayerEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPayerEnvelopes not implemented")
}
func (UnimplementedReplicationApiServer) GetInboxIds(context.Context, *GetInboxIdsRequest) (*GetInboxIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInboxIds not implemented")
}
func (UnimplementedReplicationApiServer) GetNewestEnvelope(context.Context, *GetNewestEnvelopeRequest) (*GetNewestEnvelopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewestEnvelope not implemented")
}
func (UnimplementedReplicationApiServer) mustEmbedUnimplementedReplicationApiServer() {}

// UnsafeReplicationApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplicationApiServer will
// result in compilation errors.
type UnsafeReplicationApiServer interface {
	mustEmbedUnimplementedReplicationApiServer()
}

func RegisterReplicationApiServer(s grpc.ServiceRegistrar, srv ReplicationApiServer) {
	s.RegisterService(&ReplicationApi_ServiceDesc, srv)
}

func _ReplicationApi_SubscribeOriginators_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOriginatorsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationApiServer).SubscribeOriginators(m, &replicationApiSubscribeOriginatorsServer{stream})
}

type ReplicationApi_SubscribeOriginatorsServer interface {
	Send(*SubscribeOriginatorsResponse) error
	grpc.ServerStream
}

type replicationApiSubscribeOriginatorsServer struct {
	grpc.ServerStream
}

func (x *replicationApiSubscribeOriginatorsServer) Send(m *SubscribeOriginatorsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReplicationApi_SubscribeEnvelopes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEnvelopesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationApiServer).SubscribeEnvelopes(m, &replicationApiSubscribeEnvelopesServer{stream})
}

type ReplicationApi_SubscribeEnvelopesServer interface {
	Send(*SubscribeEnvelopesResponse) error
	grpc.ServerStream
}

type replicationApiSubscribeEnvelopesServer struct {
	grpc.ServerStream
}

func (x *replicationApiSubscribeEnvelopesServer) Send(m *SubscribeEnvelopesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReplicationApi_SubscribeTopics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTopicsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ReplicationApiServer).SubscribeTopics(m, &replicationApiSubscribeTopicsServer{stream})
}

type ReplicationApi_SubscribeTopicsServer interface {
	Send(*SubscribeTopicsResponse) error
	grpc.ServerStream
}

type replicationApiSubscribeTopicsServer struct {
	grpc.ServerStream
}

func (x *replicationApiSubscribeTopicsServer) Send(m *SubscribeTopicsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ReplicationApi_QueryEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationApiServer).QueryEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationApi_QueryEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationApiServer).QueryEnvelopes(ctx, req.(*QueryEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationApi_PublishPayerEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPayerEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationApiServer).PublishPayerEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationApi_PublishPayerEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationApiServer).PublishPayerEnvelopes(ctx, req.(*PublishPayerEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationApi_GetInboxIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboxIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationApiServer).GetInboxIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationApi_GetInboxIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationApiServer).GetInboxIds(ctx, req.(*GetInboxIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicationApi_GetNewestEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewestEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicationApiServer).GetNewestEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplicationApi_GetNewestEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicationApiServer).GetNewestEnvelope(ctx, req.(*GetNewestEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplicationApi_ServiceDesc is the grpc.ServiceDesc for ReplicationApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplicationApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmtp.xmtpv4.message_api.ReplicationApi",
	HandlerType: (*ReplicationApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryEnvelopes",
			Handler:    _ReplicationApi_QueryEnvelopes_Handler,
		},
		{
			MethodName: "PublishPayerEnvelopes",
			Handler:    _ReplicationApi_PublishPayerEnvelopes_Handler,
		},
		{
			MethodName: "GetInboxIds",
			Handler:    _ReplicationApi_GetInboxIds_Handler,
		},
		{
			MethodName: "GetNewestEnvelope",
			Handler:    _ReplicationApi_GetNewestEnvelope_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOriginators",
			Handler:       _ReplicationApi_SubscribeOriginators_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEnvelopes",
			Handler:       _ReplicationApi_SubscribeEnvelopes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTopics",
			Handler:       _ReplicationApi_SubscribeTopics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xmtpv4/message_api/message_api.proto",
}
