// Notification API - Full envelope stream for push notification servers

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: xmtpv4/message_api/notification_api.proto

package message_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotificationApi_SubscribeAllEnvelopes_FullMethodName = "/xmtp.xmtpv4.message_api.NotificationApi/SubscribeAllEnvelopes"
)

// NotificationApiClient is the client API for NotificationApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationApiClient interface {
	SubscribeAllEnvelopes(ctx context.Context, in *SubscribeAllEnvelopesRequest, opts ...grpc.CallOption) (NotificationApi_SubscribeAllEnvelopesClient, error)
}

type notificationApiClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationApiClient(cc grpc.ClientConnInterface) NotificationApiClient {
	return &notificationApiClient{cc}
}

func (c *notificationApiClient) SubscribeAllEnvelopes(ctx context.Context, in *SubscribeAllEnvelopesRequest, opts ...grpc.CallOption) (NotificationApi_SubscribeAllEnvelopesClient, error) {
	stream, err := c.cc.NewStream(ctx, &NotificationApi_ServiceDesc.Streams[0], NotificationApi_SubscribeAllEnvelopes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &notificationApiSubscribeAllEnvelopesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NotificationApi_SubscribeAllEnvelopesClient interface {
	Recv() (*SubscribeEnvelopesResponse, error)
	grpc.ClientStream
}

type notificationApiSubscribeAllEnvelopesClient struct {
	grpc.ClientStream
}

func (x *notificationApiSubscribeAllEnvelopesClient) Recv() (*SubscribeEnvelopesResponse, error) {
	m := new(SubscribeEnvelopesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NotificationApiServer is the server API for NotificationApi service.
// All implementations must embed UnimplementedNotificationApiServer
// for forward compatibility
type NotificationApiServer interface {
	SubscribeAllEnvelopes(*SubscribeAllEnvelopesRequest, NotificationApi_SubscribeAllEnvelopesServer) error
	mustEmbedUnimplementedNotificationApiServer()
}

// UnimplementedNotificationApiServer must be embedded to have forward compatible implementations.
type UnimplementedNotificationApiServer struct {
}

func (UnimplementedNotificationApiServer) SubscribeAllEnvelopes(*SubscribeAllEnvelopesRequest, NotificationApi_SubscribeAllEnvelopesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeAllEnvelopes not implemented")
}
func (UnimplementedNotificationApiServer) mustEmbedUnimplementedNotificationApiServer() {}

// UnsafeNotificationApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationApiServer will
// result in compilation errors.
type UnsafeNotificationApiServer interface {
	mustEmbedUnimplementedNotificationApiServer()
}

func RegisterNotificationApiServer(s grpc.ServiceRegistrar, srv NotificationApiServer) {
	s.RegisterService(&NotificationApi_ServiceDesc, srv)
}

func _NotificationApi_SubscribeAllEnvelopes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAllEnvelopesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NotificationApiServer).SubscribeAllEnvelopes(m, &notificationApiSubscribeAllEnvelopesServer{stream})
}

type NotificationApi_SubscribeAllEnvelopesServer interface {
	Send(*SubscribeEnvelopesResponse) error
	grpc.ServerStream
}

type notificationApiSubscribeAllEnvelopesServer struct {
	grpc.ServerStream
}

func (x *notificationApiSubscribeAllEnvelopesServer) Send(m *SubscribeEnvelopesResponse) error {
	return x.ServerStream.SendMsg(m)
}

// NotificationApi_ServiceDesc is the grpc.ServiceDesc for NotificationApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmtp.xmtpv4.message_api.NotificationApi",
	HandlerType: (*NotificationApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAllEnvelopes",
			Handler:       _NotificationApi_SubscribeAllEnvelopes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xmtpv4/message_api/notification_api.proto",
}
