// Publish API - Gateway to Node publishing

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: xmtpv4/message_api/publish_api.proto

package message_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PublishApi_PublishPayerEnvelopes_FullMethodName = "/xmtp.xmtpv4.message_api.PublishApi/PublishPayerEnvelopes"
)

// PublishApiClient is the client API for PublishApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublishApiClient interface {
	PublishPayerEnvelopes(ctx context.Context, in *PublishPayerEnvelopesRequest, opts ...grpc.CallOption) (*PublishPayerEnvelopesResponse, error)
}

type publishApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPublishApiClient(cc grpc.ClientConnInterface) PublishApiClient {
	return &publishApiClient{cc}
}

func (c *publishApiClient) PublishPayerEnvelopes(ctx context.Context, in *PublishPayerEnvelopesRequest, opts ...grpc.CallOption) (*PublishPayerEnvelopesResponse, error) {
	out := new(PublishPayerEnvelopesResponse)
	err := c.cc.Invoke(ctx, PublishApi_PublishPayerEnvelopes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishApiServer is the server API for PublishApi service.
// All implementations must embed UnimplementedPublishApiServer
// for forward compatibility
type PublishApiServer interface {
	PublishPayerEnvelopes(context.Context, *PublishPayerEnvelopesRequest) (*PublishPayerEnvelopesResponse, error)
	mustEmbedUnimplementedPublishApiServer()
}

// UnimplementedPublishApiServer must be embedded to have forward compatible implementations.
type UnimplementedPublishApiServer struct {
}

func (UnimplementedPublishApiServer) PublishPayerEnvelopes(context.Context, *PublishPayerEnvelopesRequest) (*PublishPayerEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPayerEnvelopes not implemented")
}
func (UnimplementedPublishApiServer) mustEmbedUnimplementedPublishApiServer() {}

// UnsafePublishApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublishApiServer will
// result in compilation errors.
type UnsafePublishApiServer interface {
	mustEmbedUnimplementedPublishApiServer()
}

func RegisterPublishApiServer(s grpc.ServiceRegistrar, srv PublishApiServer) {
	s.RegisterService(&PublishApi_ServiceDesc, srv)
}

func _PublishApi_PublishPayerEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPayerEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishApiServer).PublishPayerEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublishApi_PublishPayerEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishApiServer).PublishPayerEnvelopes(ctx, req.(*PublishPayerEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublishApi_ServiceDesc is the grpc.ServiceDesc for PublishApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublishApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmtp.xmtpv4.message_api.PublishApi",
	HandlerType: (*PublishApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishPayerEnvelopes",
			Handler:    _PublishApi_PublishPayerEnvelopes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xmtpv4/message_api/publish_api.proto",
}
