// Query API - Client to Node queries and subscriptions

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: xmtpv4/message_api/query_api.proto

package message_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QueryApi_QueryEnvelopes_FullMethodName    = "/xmtp.xmtpv4.message_api.QueryApi/QueryEnvelopes"
	QueryApi_SubscribeTopics_FullMethodName   = "/xmtp.xmtpv4.message_api.QueryApi/SubscribeTopics"
	QueryApi_GetInboxIds_FullMethodName       = "/xmtp.xmtpv4.message_api.QueryApi/GetInboxIds"
	QueryApi_GetNewestEnvelope_FullMethodName = "/xmtp.xmtpv4.message_api.QueryApi/GetNewestEnvelope"
)

// QueryApiClient is the client API for QueryApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryApiClient interface {
	QueryEnvelopes(ctx context.Context, in *QueryEnvelopesRequest, opts ...grpc.CallOption) (*QueryEnvelopesResponse, error)
	SubscribeTopics(ctx context.Context, in *SubscribeTopicsRequest, opts ...grpc.CallOption) (QueryApi_SubscribeTopicsClient, error)
	GetInboxIds(ctx context.Context, in *GetInboxIdsRequest, opts ...grpc.CallOption) (*GetInboxIdsResponse, error)
	GetNewestEnvelope(ctx context.Context, in *GetNewestEnvelopeRequest, opts ...grpc.CallOption) (*GetNewestEnvelopeResponse, error)
}

type queryApiClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryApiClient(cc grpc.ClientConnInterface) QueryApiClient {
	return &queryApiClient{cc}
}

func (c *queryApiClient) QueryEnvelopes(ctx context.Context, in *QueryEnvelopesRequest, opts ...grpc.CallOption) (*QueryEnvelopesResponse, error) {
	out := new(QueryEnvelopesResponse)
	err := c.cc.Invoke(ctx, QueryApi_QueryEnvelopes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryApiClient) SubscribeTopics(ctx context.Context, in *SubscribeTopicsRequest, opts ...grpc.CallOption) (QueryApi_SubscribeTopicsClient, error) {
	stream, err := c.cc.NewStream(ctx, &QueryApi_ServiceDesc.Streams[0], QueryApi_SubscribeTopics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queryApiSubscribeTopicsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueryApi_SubscribeTopicsClient interface {
	Recv() (*SubscribeTopicsResponse, error)
	grpc.ClientStream
}

type queryApiSubscribeTopicsClient struct {
	grpc.ClientStream
}

func (x *queryApiSubscribeTopicsClient) Recv() (*SubscribeTopicsResponse, error) {
	m := new(SubscribeTopicsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryApiClient) GetInboxIds(ctx context.Context, in *GetInboxIdsRequest, opts ...grpc.CallOption) (*GetInboxIdsResponse, error) {
	out := new(GetInboxIdsResponse)
	err := c.cc.Invoke(ctx, QueryApi_GetInboxIds_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryApiClient) GetNewestEnvelope(ctx context.Context, in *GetNewestEnvelopeRequest, opts ...grpc.CallOption) (*GetNewestEnvelopeResponse, error) {
	out := new(GetNewestEnvelopeResponse)
	err := c.cc.Invoke(ctx, QueryApi_GetNewestEnvelope_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryApiServer is the server API for QueryApi service.
// All implementations must embed UnimplementedQueryApiServer
// for forward compatibility
type QueryApiServer interface {
	QueryEnvelopes(context.Context, *QueryEnvelopesRequest) (*QueryEnvelopesResponse, error)
	SubscribeTopics(*SubscribeTopicsRequest, QueryApi_SubscribeTopicsServer) error
	GetInboxIds(context.Context, *GetInboxIdsRequest) (*GetInboxIdsResponse, error)
	GetNewestEnvelope(context.Context, *GetNewestEnvelopeRequest) (*GetNewestEnvelopeResponse, error)
	mustEmbedUnimplementedQueryApiServer()
}

// UnimplementedQueryApiServer must be embedded to have forward compatible implementations.
type UnimplementedQueryApiServer struct {
}

func (UnimplementedQueryApiServer) QueryEnvelopes(context.Context, *QueryEnvelopesRequest) (*QueryEnvelopesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEnvelopes not implemented")
}
func (UnimplementedQueryApiServer) SubscribeTopics(*SubscribeTopicsRequest, QueryApi_SubscribeTopicsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTopics not implemented")
}
func (UnimplementedQueryApiServer) GetInboxIds(context.Context, *GetInboxIdsRequest) (*GetInboxIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInboxIds not implemented")
}
func (UnimplementedQueryApiServer) GetNewestEnvelope(context.Context, *GetNewestEnvelopeRequest) (*GetNewestEnvelopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNewestEnvelope not implemented")
}
func (UnimplementedQueryApiServer) mustEmbedUnimplementedQueryApiServer() {}

// UnsafeQueryApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryApiServer will
// result in compilation errors.
type UnsafeQueryApiServer interface {
	mustEmbedUnimplementedQueryApiServer()
}

func RegisterQueryApiServer(s grpc.ServiceRegistrar, srv QueryApiServer) {
	s.RegisterService(&QueryApi_ServiceDesc, srv)
}

func _QueryApi_QueryEnvelopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEnvelopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryApiServer).QueryEnvelopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryApi_QueryEnvelopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryApiServer).QueryEnvelopes(ctx, req.(*QueryEnvelopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryApi_SubscribeTopics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTopicsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryApiServer).SubscribeTopics(m, &queryApiSubscribeTopicsServer{stream})
}

type QueryApi_SubscribeTopicsServer interface {
	Send(*SubscribeTopicsResponse) error
	grpc.ServerStream
}

type queryApiSubscribeTopicsServer struct {
	grpc.ServerStream
}

func (x *queryApiSubscribeTopicsServer) Send(m *SubscribeTopicsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _QueryApi_GetInboxIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboxIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryApiServer).GetInboxIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryApi_GetInboxIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryApiServer).GetInboxIds(ctx, req.(*GetInboxIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryApi_GetNewestEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewestEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryApiServer).GetNewestEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryApi_GetNewestEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryApiServer).GetNewestEnvelope(ctx, req.(*GetNewestEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryApi_ServiceDesc is the grpc.ServiceDesc for QueryApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xmtp.xmtpv4.message_api.QueryApi",
	HandlerType: (*QueryApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryEnvelopes",
			Handler:    _QueryApi_QueryEnvelopes_Handler,
		},
		{
			MethodName: "GetInboxIds",
			Handler:    _QueryApi_GetInboxIds_Handler,
		},
		{
			MethodName: "GetNewestEnvelope",
			Handler:    _QueryApi_GetNewestEnvelope_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTopics",
			Handler:       _QueryApi_SubscribeTopics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xmtpv4/message_api/query_api.proto",
}
