#!/bin/bash
set -eo pipefail

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-xmtp/xmtpd-e2e}"

DOCKER_E2E_IMAGE="${DOCKER_E2E_IMAGE:-${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}}"

GIT_COMMIT="$(git rev-parse HEAD)"
GO_VERSION="$(go list -f "{{.GoVersion}}" -m)"

docker buildx build \
    --platform linux/amd64 \
    --tag "${DOCKER_E2E_IMAGE}" \
    --build-arg="GO_VERSION=${GO_VERSION}" \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    -f dev/docker/e2e/Dockerfile \
    .

docker push "${DOCKER_E2E_IMAGE}"

docker inspect --format='{{index .RepoDigests 0}}' "${DOCKER_E2E_IMAGE}"
# TODO: fix GH workflow that depends on the output of this script being only the image+sha and nothing else
