#!/usr/bin/env sh
set -e

go mod download

COMMIT=$(git describe HEAD --tags --long)
LD_FLAGS="-X 'main.Commit=${COMMIT}'"

for dir in ./cmd/*; do
    if [ -d "$dir" ]; then
        go build -tags="gowaku_no_rln" -ldflags="${LD_FLAGS}" -o "./bin/${dir##*/}" "${dir}" &
    fi
done

wait
