#!/bin/bash
set -e

MESSAGE_DB_DSN="postgres://postgres:xmtp@localhost:15432/postgres?sslmode=disable"
AUTHZ_DB_DSN="postgres://postgres:xmtp@localhost:15432/postgres?sslmode=disable"

go run cmd/xmtpd/main.go \
    --message-db-connection-string "${MESSAGE_DB_DSN}" \
    --message-db-reader-connection-string "${MESSAGE_DB_DSN}" \
    --authz-db-connection-string "${AUTHZ_DB_DSN}" \
    --metrics \
    --metrics-period 5s \
    --go-profiling \
    "$@"
