#!/bin/bash
set -e

MESSAGE_DB_DSN="postgres://postgres:xmtp@localhost:15432/postgres?sslmode=disable"
MLS_DB_DSN="postgres://postgres:xmtp@localhost:7654/postgres?sslmode=disable"
AUTHZ_DB_DSN="postgres://postgres:xmtp@localhost:6543/postgres?sslmode=disable"
NODE_KEY="8a30dcb604b0b53627a5adc054dbf434b446628d4bd1eccc681d223f0550ce67"

go run \
    -ldflags="-X main.Commit=$(git describe HEAD --tags --long)" \
    cmd/xmtpd/main.go \
    --nodekey "${NODE_KEY}" \
    --metrics \
    --metrics-period 5s \
    --store.enable \
    --store.db-connection-string "${MESSAGE_DB_DSN}" \
    --store.reader-db-connection-string "${MESSAGE_DB_DSN}" \
    --store.metrics-period 5s \
    --mls-store.db-connection-string "${MLS_DB_DSN}" \
    --mls-validation.grpc-address=validation:50051 \
    --authz-db-connection-string "${AUTHZ_DB_DSN}" \
    --go-profiling \
    "$@"
