#!/bin/bash
#
# Open shell in the node-0 container of the node-0 node in dev cluster.
# Assumes aws cli is installed and configured as per
# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html
# https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-install-plugin.html

region=us-east-2
cluster=dev
task=node-0
container=$task
task=$(aws --region $region --query 'taskArns[0]' --output text ecs list-tasks --cluster $cluster --family $task)
aws --region $region ecs execute-command \
    --cluster $cluster \
    --task $task \
    --container $container \
    --interactive \
    --command "/bin/sh"