#!/bin/bash
set -e

PORT="${PORT:-9002}"

dev/run \
    --api.write-to-crdt-ds \
    --api.read-from-crdt-ds \
    --store \
    --filter \
    --lightpush \
    --ws \
    --ws-port="${PORT}" \
    "$@"
