#!/bin/bash
set -e

PROJECT_GO_VERSION="$(grep "^go " go.mod | { read -r _ v; echo "${v}"; })"
if ! which go &>/dev/null; then brew install "go@${PROJECT_GO_VERSION}"; fi

GO_VERSION_FULL="$(go version | { read -r _ _ v _; echo "${v#go}"; })"
GO_VERSION="${GO_VERSION_FULL%.*}"

if [ "${GO_VERSION}" != "${PROJECT_GO_VERSION}" ]; then
    brew uninstall go
    brew install "go@${PROJECT_GO_VERSION}"
fi

go mod tidy

if ! which chronic &>/dev/null; then brew install moreutils; fi
if ! which golangci-lint &>/dev/null; then brew install golangci-lint; fi
if ! which shellcheck &>/dev/null; then brew install shellcheck; fi
if ! which mockgen &>/dev/null; then go install github.com/golang/mock/mockgen@latest; fi

dev/generate
dev/docker/up
dev/e2e/docker/up
