#!/bin/bash
set -eo pipefail

secret="$(kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode)"
echo -n "${secret}" | pbcopy

echo "Password has been copied to your clipboard"
