// Private Key Storage
//
// Following definitions are not used in the protocol, instead
// they provide a way for encoding private keys for storage.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: message_contents/private_preferences.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PrivatePreferencesAction is a message used to update the client's
// preference store. The only current actions are allow and block.
// Other actions may be added later
type PrivatePreferencesAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to MessageType:
	//
	//	*PrivatePreferencesAction_Allow_
	//	*PrivatePreferencesAction_Block_
	MessageType isPrivatePreferencesAction_MessageType `protobuf_oneof:"message_type"`
}

func (x *PrivatePreferencesAction) Reset() {
	*x = PrivatePreferencesAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_private_preferences_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivatePreferencesAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePreferencesAction) ProtoMessage() {}

func (x *PrivatePreferencesAction) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_private_preferences_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePreferencesAction.ProtoReflect.Descriptor instead.
func (*PrivatePreferencesAction) Descriptor() ([]byte, []int) {
	return file_message_contents_private_preferences_proto_rawDescGZIP(), []int{0}
}

func (m *PrivatePreferencesAction) GetMessageType() isPrivatePreferencesAction_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (x *PrivatePreferencesAction) GetAllow() *PrivatePreferencesAction_Allow {
	if x, ok := x.GetMessageType().(*PrivatePreferencesAction_Allow_); ok {
		return x.Allow
	}
	return nil
}

func (x *PrivatePreferencesAction) GetBlock() *PrivatePreferencesAction_Block {
	if x, ok := x.GetMessageType().(*PrivatePreferencesAction_Block_); ok {
		return x.Block
	}
	return nil
}

type isPrivatePreferencesAction_MessageType interface {
	isPrivatePreferencesAction_MessageType()
}

type PrivatePreferencesAction_Allow_ struct {
	Allow *PrivatePreferencesAction_Allow `protobuf:"bytes,1,opt,name=allow,proto3,oneof"`
}

type PrivatePreferencesAction_Block_ struct {
	Block *PrivatePreferencesAction_Block `protobuf:"bytes,2,opt,name=block,proto3,oneof"`
}

func (*PrivatePreferencesAction_Allow_) isPrivatePreferencesAction_MessageType() {}

func (*PrivatePreferencesAction_Block_) isPrivatePreferencesAction_MessageType() {}

// The payload that goes over the wire
type PrivatePreferencesPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Version:
	//
	//	*PrivatePreferencesPayload_V1
	Version isPrivatePreferencesPayload_Version `protobuf_oneof:"version"`
}

func (x *PrivatePreferencesPayload) Reset() {
	*x = PrivatePreferencesPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_private_preferences_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivatePreferencesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePreferencesPayload) ProtoMessage() {}

func (x *PrivatePreferencesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_private_preferences_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePreferencesPayload.ProtoReflect.Descriptor instead.
func (*PrivatePreferencesPayload) Descriptor() ([]byte, []int) {
	return file_message_contents_private_preferences_proto_rawDescGZIP(), []int{1}
}

func (m *PrivatePreferencesPayload) GetVersion() isPrivatePreferencesPayload_Version {
	if m != nil {
		return m.Version
	}
	return nil
}

func (x *PrivatePreferencesPayload) GetV1() *Ciphertext {
	if x, ok := x.GetVersion().(*PrivatePreferencesPayload_V1); ok {
		return x.V1
	}
	return nil
}

type isPrivatePreferencesPayload_Version interface {
	isPrivatePreferencesPayload_Version()
}

type PrivatePreferencesPayload_V1 struct {
	V1 *Ciphertext `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*PrivatePreferencesPayload_V1) isPrivatePreferencesPayload_Version() {}

// Add the given wallet addresses to the allow list
type PrivatePreferencesAction_Allow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddresses []string `protobuf:"bytes,1,rep,name=wallet_addresses,json=walletAddresses,proto3" json:"wallet_addresses,omitempty"`
}

func (x *PrivatePreferencesAction_Allow) Reset() {
	*x = PrivatePreferencesAction_Allow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_private_preferences_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivatePreferencesAction_Allow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePreferencesAction_Allow) ProtoMessage() {}

func (x *PrivatePreferencesAction_Allow) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_private_preferences_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePreferencesAction_Allow.ProtoReflect.Descriptor instead.
func (*PrivatePreferencesAction_Allow) Descriptor() ([]byte, []int) {
	return file_message_contents_private_preferences_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PrivatePreferencesAction_Allow) GetWalletAddresses() []string {
	if x != nil {
		return x.WalletAddresses
	}
	return nil
}

// Add the given wallet addresses to the block list
type PrivatePreferencesAction_Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddresses []string `protobuf:"bytes,1,rep,name=wallet_addresses,json=walletAddresses,proto3" json:"wallet_addresses,omitempty"`
}

func (x *PrivatePreferencesAction_Block) Reset() {
	*x = PrivatePreferencesAction_Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_contents_private_preferences_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrivatePreferencesAction_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivatePreferencesAction_Block) ProtoMessage() {}

func (x *PrivatePreferencesAction_Block) ProtoReflect() protoreflect.Message {
	mi := &file_message_contents_private_preferences_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivatePreferencesAction_Block.ProtoReflect.Descriptor instead.
func (*PrivatePreferencesAction_Block) Descriptor() ([]byte, []int) {
	return file_message_contents_private_preferences_proto_rawDescGZIP(), []int{0, 1}
}

func (x *PrivatePreferencesAction_Block) GetWalletAddresses() []string {
	if x != nil {
		return x.WalletAddresses
	}
	return nil
}

var File_message_contents_private_preferences_proto protoreflect.FileDescriptor

var file_message_contents_private_preferences_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x78, 0x6d,
	0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x1a, 0x21, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x63, 0x69, 0x70, 0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x02, 0x0a, 0x18, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x4d, 0x0a, 0x05, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x35, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x12, 0x4d, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x35, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x1a, 0x32, 0x0a, 0x05, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x12, 0x29, 0x0a, 0x10, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x65, 0x73, 0x1a, 0x32, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x29,
	0x0a, 0x10, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x42, 0x0e, 0x0a, 0x0c, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x5b, 0x0a, 0x19, 0x50, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x50,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x33, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x78, 0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x02, 0x76, 0x31, 0x42, 0x09, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0xde, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x78,
	0x6d, 0x74, 0x70, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x42, 0x17, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x6d, 0x74, 0x70,
	0x2f, 0x78, 0x6d, 0x74, 0x70, 0x2d, 0x6e, 0x6f, 0x64, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0xa2, 0x02, 0x03, 0x58, 0x4d, 0x58, 0xaa, 0x02,
	0x14, 0x58, 0x6d, 0x74, 0x70, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0xca, 0x02, 0x14, 0x58, 0x6d, 0x74, 0x70, 0x5c, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0xe2, 0x02, 0x20, 0x58,
	0x6d, 0x74, 0x70, 0x5c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea,
	0x02, 0x15, 0x58, 0x6d, 0x74, 0x70, 0x3a, 0x3a, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_contents_private_preferences_proto_rawDescOnce sync.Once
	file_message_contents_private_preferences_proto_rawDescData = file_message_contents_private_preferences_proto_rawDesc
)

func file_message_contents_private_preferences_proto_rawDescGZIP() []byte {
	file_message_contents_private_preferences_proto_rawDescOnce.Do(func() {
		file_message_contents_private_preferences_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_contents_private_preferences_proto_rawDescData)
	})
	return file_message_contents_private_preferences_proto_rawDescData
}

var file_message_contents_private_preferences_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_contents_private_preferences_proto_goTypes = []interface{}{
	(*PrivatePreferencesAction)(nil),       // 0: xmtp.message_contents.PrivatePreferencesAction
	(*PrivatePreferencesPayload)(nil),      // 1: xmtp.message_contents.PrivatePreferencesPayload
	(*PrivatePreferencesAction_Allow)(nil), // 2: xmtp.message_contents.PrivatePreferencesAction.Allow
	(*PrivatePreferencesAction_Block)(nil), // 3: xmtp.message_contents.PrivatePreferencesAction.Block
	(*Ciphertext)(nil),                     // 4: xmtp.message_contents.Ciphertext
}
var file_message_contents_private_preferences_proto_depIdxs = []int32{
	2, // 0: xmtp.message_contents.PrivatePreferencesAction.allow:type_name -> xmtp.message_contents.PrivatePreferencesAction.Allow
	3, // 1: xmtp.message_contents.PrivatePreferencesAction.block:type_name -> xmtp.message_contents.PrivatePreferencesAction.Block
	4, // 2: xmtp.message_contents.PrivatePreferencesPayload.v1:type_name -> xmtp.message_contents.Ciphertext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_contents_private_preferences_proto_init() }
func file_message_contents_private_preferences_proto_init() {
	if File_message_contents_private_preferences_proto != nil {
		return
	}
	file_message_contents_ciphertext_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_message_contents_private_preferences_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivatePreferencesAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_private_preferences_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivatePreferencesPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_private_preferences_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivatePreferencesAction_Allow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_contents_private_preferences_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrivatePreferencesAction_Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_message_contents_private_preferences_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PrivatePreferencesAction_Allow_)(nil),
		(*PrivatePreferencesAction_Block_)(nil),
	}
	file_message_contents_private_preferences_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*PrivatePreferencesPayload_V1)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_contents_private_preferences_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_contents_private_preferences_proto_goTypes,
		DependencyIndexes: file_message_contents_private_preferences_proto_depIdxs,
		MessageInfos:      file_message_contents_private_preferences_proto_msgTypes,
	}.Build()
	File_message_contents_private_preferences_proto = out.File
	file_message_contents_private_preferences_proto_rawDesc = nil
	file_message_contents_private_preferences_proto_goTypes = nil
	file_message_contents_private_preferences_proto_depIdxs = nil
}
