// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"database/sql"
	"time"
)

type AddressLog struct {
	Address               string
	InboxID               []byte
	AssociationSequenceID sql.NullInt64
	RevocationSequenceID  sql.NullInt64
}

type CommitLog struct {
	ID             int64
	CreatedAt      time.Time
	GroupID        []byte
	EncryptedEntry []byte
}

type CommitLogV2 struct {
	ID                  int64
	CreatedAt           time.Time
	GroupID             []byte
	SerializedEntry     []byte
	SerializedSignature []byte
}

type GroupMessage struct {
	ID              int64
	CreatedAt       time.Time
	GroupID         []byte
	Data            []byte
	GroupIDDataHash []byte
	IsCommit        sql.NullBool
	SenderHmac      []byte
	ShouldPush      sql.NullBool
}

type Inbox struct {
	ID        []byte
	UpdatedAt sql.NullTime
}

type InboxLog struct {
	SequenceID          int64
	InboxID             []byte
	ServerTimestampNs   int64
	IdentityUpdateProto []byte
}

type Installation struct {
	ID         []byte
	CreatedAt  int64
	UpdatedAt  int64
	KeyPackage []byte
	IsAppended sql.NullBool
}

type KeyPackage struct {
	SequenceID     int64
	InstallationID []byte
	KeyPackage     []byte
	CreatedAt      int64
}

type WelcomeMessage struct {
	ID                      int64
	CreatedAt               time.Time
	InstallationKey         []byte
	Data                    []byte
	HpkePublicKey           []byte
	InstallationKeyDataHash []byte
	WrapperAlgorithm        int16
	WelcomeMetadata         []byte
}
