#!/usr/bin/env sh
set -e

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-xmtp/xmtpd-e2e}"
GIT_COMMIT="$(git rev-parse HEAD)"

DOCKER_IMAGE_SHA=$(docker buildx build \
    --platform linux/amd64 \
    --tag "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    -f dev/e2e/Dockerfile \
    -q \
    --push \
    .)

echo "${DOCKER_IMAGE_NAME}@${DOCKER_IMAGE_SHA}"
