name: E2E
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run E2E
        run: |
          dev/k8s/up
          export KUBECONFIG="${PWD}/dev/terraform/plans/devnet-local/.xmtp/kubeconfig.yaml"
          dev/k8s/e2e-run
