name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17.0" # The Go version to download (if necessary) and use.
      - uses: actions/checkout@v2
      - run: make test
