// Message content encoding structures
// Copied from V2 code so that we can eventually retire all V2 message content

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mls/message_contents/encryption.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WelcomeEncryption
type WelcomeEncryption int32

const (
	WelcomeEncryption_WELCOME_ENCRYPTION_UNSPECIFIED     WelcomeEncryption = 0
	WelcomeEncryption_WELCOME_ENCRYPTION_CURVE25519      WelcomeEncryption = 1
	WelcomeEncryption_WELCOME_ENCRYPTION_XWING_MLKEM_512 WelcomeEncryption = 2
)

// Enum value maps for WelcomeEncryption.
var (
	WelcomeEncryption_name = map[int32]string{
		0: "WELCOME_ENCRYPTION_UNSPECIFIED",
		1: "WELCOME_ENCRYPTION_CURVE25519",
		2: "WELCOME_ENCRYPTION_XWING_MLKEM_512",
	}
	WelcomeEncryption_value = map[string]int32{
		"WELCOME_ENCRYPTION_UNSPECIFIED":     0,
		"WELCOME_ENCRYPTION_CURVE25519":      1,
		"WELCOME_ENCRYPTION_XWING_MLKEM_512": 2,
	}
)

func (x WelcomeEncryption) Enum() *WelcomeEncryption {
	p := new(WelcomeEncryption)
	*p = x
	return p
}

func (x WelcomeEncryption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WelcomeEncryption) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_message_contents_encryption_proto_enumTypes[0].Descriptor()
}

func (WelcomeEncryption) Type() protoreflect.EnumType {
	return &file_mls_message_contents_encryption_proto_enumTypes[0]
}

func (x WelcomeEncryption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WelcomeEncryption.Descriptor instead.
func (WelcomeEncryption) EnumDescriptor() ([]byte, []int) {
	return file_mls_message_contents_encryption_proto_rawDescGZIP(), []int{0}
}

var File_mls_message_contents_encryption_proto protoreflect.FileDescriptor

const file_mls_message_contents_encryption_proto_rawDesc = "" +
	"\n" +
	"%mls/message_contents/encryption.proto\x12\x19xmtp.mls.message_contents*\x82\x01\n" +
	"\x11WelcomeEncryption\x12\"\n" +
	"\x1eWELCOME_ENCRYPTION_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dWELCOME_ENCRYPTION_CURVE25519\x10\x01\x12&\n" +
	"\"WELCOME_ENCRYPTION_XWING_MLKEM_512\x10\x02B\xef\x01\n" +
	"\x1dcom.xmtp.mls.message_contentsB\x0fEncryptionProtoP\x01Z;github.com/xmtp/xmtp-node-go/pkg/proto/mls/message_contents\xa2\x02\x03XMM\xaa\x02\x18Xmtp.Mls.MessageContents\xca\x02\x18Xmtp\\Mls\\MessageContents\xe2\x02$Xmtp\\Mls\\MessageContents\\GPBMetadata\xea\x02\x1aXmtp::Mls::MessageContentsb\x06proto3"

var (
	file_mls_message_contents_encryption_proto_rawDescOnce sync.Once
	file_mls_message_contents_encryption_proto_rawDescData []byte
)

func file_mls_message_contents_encryption_proto_rawDescGZIP() []byte {
	file_mls_message_contents_encryption_proto_rawDescOnce.Do(func() {
		file_mls_message_contents_encryption_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_message_contents_encryption_proto_rawDesc), len(file_mls_message_contents_encryption_proto_rawDesc)))
	})
	return file_mls_message_contents_encryption_proto_rawDescData
}

var file_mls_message_contents_encryption_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mls_message_contents_encryption_proto_goTypes = []any{
	(WelcomeEncryption)(0), // 0: xmtp.mls.message_contents.WelcomeEncryption
}
var file_mls_message_contents_encryption_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mls_message_contents_encryption_proto_init() }
func file_mls_message_contents_encryption_proto_init() {
	if File_mls_message_contents_encryption_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_message_contents_encryption_proto_rawDesc), len(file_mls_message_contents_encryption_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_message_contents_encryption_proto_goTypes,
		DependencyIndexes: file_mls_message_contents_encryption_proto_depIdxs,
		EnumInfos:         file_mls_message_contents_encryption_proto_enumTypes,
	}.Build()
	File_mls_message_contents_encryption_proto = out.File
	file_mls_message_contents_encryption_proto_goTypes = nil
	file_mls_message_contents_encryption_proto_depIdxs = nil
}
