// WelcomePointer is used to point to the welcome message for several installations at once to save overhead

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: mls/message_contents/welcome_pointer.proto

package message_contents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomePointeeEncryptionAeadType int32

const (
	WelcomePointeeEncryptionAeadType_WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_UNSPECIFIED WelcomePointeeEncryptionAeadType = 0
	// Use same encoding as openmls::AeadType
	WelcomePointeeEncryptionAeadType_WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_CHACHA20_POLY1305 WelcomePointeeEncryptionAeadType = 3
)

// Enum value maps for WelcomePointeeEncryptionAeadType.
var (
	WelcomePointeeEncryptionAeadType_name = map[int32]string{
		0: "WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_UNSPECIFIED",
		3: "WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_CHACHA20_POLY1305",
	}
	WelcomePointeeEncryptionAeadType_value = map[string]int32{
		"WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_UNSPECIFIED":       0,
		"WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_CHACHA20_POLY1305": 3,
	}
)

func (x WelcomePointeeEncryptionAeadType) Enum() *WelcomePointeeEncryptionAeadType {
	p := new(WelcomePointeeEncryptionAeadType)
	*p = x
	return p
}

func (x WelcomePointeeEncryptionAeadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WelcomePointeeEncryptionAeadType) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_message_contents_welcome_pointer_proto_enumTypes[0].Descriptor()
}

func (WelcomePointeeEncryptionAeadType) Type() protoreflect.EnumType {
	return &file_mls_message_contents_welcome_pointer_proto_enumTypes[0]
}

func (x WelcomePointeeEncryptionAeadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WelcomePointeeEncryptionAeadType.Descriptor instead.
func (WelcomePointeeEncryptionAeadType) EnumDescriptor() ([]byte, []int) {
	return file_mls_message_contents_welcome_pointer_proto_rawDescGZIP(), []int{0}
}

// MUST match the WelcomeWrapperAlgorithm enum values without 25519 so that the i32 transformations are compatible
type WelcomePointerWrapperAlgorithm int32

const (
	WelcomePointerWrapperAlgorithm_WELCOME_POINTER_WRAPPER_ALGORITHM_UNSPECIFIED             WelcomePointerWrapperAlgorithm = 0
	WelcomePointerWrapperAlgorithm_WELCOME_POINTER_WRAPPER_ALGORITHM_XWING_MLKEM_768_DRAFT_6 WelcomePointerWrapperAlgorithm = 2
)

// Enum value maps for WelcomePointerWrapperAlgorithm.
var (
	WelcomePointerWrapperAlgorithm_name = map[int32]string{
		0: "WELCOME_POINTER_WRAPPER_ALGORITHM_UNSPECIFIED",
		2: "WELCOME_POINTER_WRAPPER_ALGORITHM_XWING_MLKEM_768_DRAFT_6",
	}
	WelcomePointerWrapperAlgorithm_value = map[string]int32{
		"WELCOME_POINTER_WRAPPER_ALGORITHM_UNSPECIFIED":             0,
		"WELCOME_POINTER_WRAPPER_ALGORITHM_XWING_MLKEM_768_DRAFT_6": 2,
	}
)

func (x WelcomePointerWrapperAlgorithm) Enum() *WelcomePointerWrapperAlgorithm {
	p := new(WelcomePointerWrapperAlgorithm)
	*p = x
	return p
}

func (x WelcomePointerWrapperAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WelcomePointerWrapperAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_mls_message_contents_welcome_pointer_proto_enumTypes[1].Descriptor()
}

func (WelcomePointerWrapperAlgorithm) Type() protoreflect.EnumType {
	return &file_mls_message_contents_welcome_pointer_proto_enumTypes[1]
}

func (x WelcomePointerWrapperAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WelcomePointerWrapperAlgorithm.Descriptor instead.
func (WelcomePointerWrapperAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_mls_message_contents_welcome_pointer_proto_rawDescGZIP(), []int{1}
}

// A WelcomePointer is used to point to the welcome message for several installations at once to save overhead
type WelcomePointer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Version:
	//
	//	*WelcomePointer_V1_
	Version       isWelcomePointer_Version `protobuf_oneof:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomePointer) Reset() {
	*x = WelcomePointer{}
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomePointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePointer) ProtoMessage() {}

func (x *WelcomePointer) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePointer.ProtoReflect.Descriptor instead.
func (*WelcomePointer) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_welcome_pointer_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomePointer) GetVersion() isWelcomePointer_Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *WelcomePointer) GetV1() *WelcomePointer_V1 {
	if x != nil {
		if x, ok := x.Version.(*WelcomePointer_V1_); ok {
			return x.V1
		}
	}
	return nil
}

type isWelcomePointer_Version interface {
	isWelcomePointer_Version()
}

type WelcomePointer_V1_ struct {
	V1 *WelcomePointer_V1 `protobuf:"bytes,1,opt,name=v1,proto3,oneof"`
}

func (*WelcomePointer_V1_) isWelcomePointer_Version() {}

// Extension message that indicates the types of encryption supported by a client
type WelcomePointeeEncryptionAeadTypesExtension struct {
	state              protoimpl.MessageState             `protogen:"open.v1"`
	SupportedAeadTypes []WelcomePointeeEncryptionAeadType `protobuf:"varint,1,rep,packed,name=supported_aead_types,json=supportedAeadTypes,proto3,enum=xmtp.mls.message_contents.WelcomePointeeEncryptionAeadType" json:"supported_aead_types,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WelcomePointeeEncryptionAeadTypesExtension) Reset() {
	*x = WelcomePointeeEncryptionAeadTypesExtension{}
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomePointeeEncryptionAeadTypesExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePointeeEncryptionAeadTypesExtension) ProtoMessage() {}

func (x *WelcomePointeeEncryptionAeadTypesExtension) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePointeeEncryptionAeadTypesExtension.ProtoReflect.Descriptor instead.
func (*WelcomePointeeEncryptionAeadTypesExtension) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_welcome_pointer_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomePointeeEncryptionAeadTypesExtension) GetSupportedAeadTypes() []WelcomePointeeEncryptionAeadType {
	if x != nil {
		return x.SupportedAeadTypes
	}
	return nil
}

type WelcomePointer_V1 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The topic of the welcome message. For V1, this means that it will be the first message in the topic, so no other identifier is required
	Destination []byte `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	// The algorithm used to encrypt the welcome pointer
	AeadType WelcomePointeeEncryptionAeadType `protobuf:"varint,2,opt,name=aead_type,json=aeadType,proto3,enum=xmtp.mls.message_contents.WelcomePointeeEncryptionAeadType" json:"aead_type,omitempty"`
	// The encryption key of the welcome message. Must match key size specified by the aead_type.
	EncryptionKey []byte `protobuf:"bytes,3,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`
	// Nonces used to encrypt the welcome pointer fields. Must match nonce size specified by the aead_type.
	Nonces        [][]byte `protobuf:"bytes,4,rep,name=nonces,proto3" json:"nonces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomePointer_V1) Reset() {
	*x = WelcomePointer_V1{}
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomePointer_V1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomePointer_V1) ProtoMessage() {}

func (x *WelcomePointer_V1) ProtoReflect() protoreflect.Message {
	mi := &file_mls_message_contents_welcome_pointer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomePointer_V1.ProtoReflect.Descriptor instead.
func (*WelcomePointer_V1) Descriptor() ([]byte, []int) {
	return file_mls_message_contents_welcome_pointer_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WelcomePointer_V1) GetDestination() []byte {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *WelcomePointer_V1) GetAeadType() WelcomePointeeEncryptionAeadType {
	if x != nil {
		return x.AeadType
	}
	return WelcomePointeeEncryptionAeadType_WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_UNSPECIFIED
}

func (x *WelcomePointer_V1) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *WelcomePointer_V1) GetNonces() [][]byte {
	if x != nil {
		return x.Nonces
	}
	return nil
}

var File_mls_message_contents_welcome_pointer_proto protoreflect.FileDescriptor

const file_mls_message_contents_welcome_pointer_proto_rawDesc = "" +
	"\n" +
	"*mls/message_contents/welcome_pointer.proto\x12\x19xmtp.mls.message_contents\"\x9d\x02\n" +
	"\x0eWelcomePointer\x12>\n" +
	"\x02v1\x18\x01 \x01(\v2,.xmtp.mls.message_contents.WelcomePointer.V1H\x00R\x02v1\x1a\xbf\x01\n" +
	"\x02V1\x12 \n" +
	"\vdestination\x18\x01 \x01(\fR\vdestination\x12X\n" +
	"\taead_type\x18\x02 \x01(\x0e2;.xmtp.mls.message_contents.WelcomePointeeEncryptionAeadTypeR\baeadType\x12%\n" +
	"\x0eencryption_key\x18\x03 \x01(\fR\rencryptionKey\x12\x16\n" +
	"\x06nonces\x18\x04 \x03(\fR\x06noncesB\t\n" +
	"\aversion\"\x9b\x01\n" +
	"*WelcomePointeeEncryptionAeadTypesExtension\x12m\n" +
	"\x14supported_aead_types\x18\x01 \x03(\x0e2;.xmtp.mls.message_contents.WelcomePointeeEncryptionAeadTypeR\x12supportedAeadTypes*\x94\x01\n" +
	" WelcomePointeeEncryptionAeadType\x124\n" +
	"0WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_UNSPECIFIED\x10\x00\x12:\n" +
	"6WELCOME_POINTEE_ENCRYPTION_AEAD_TYPE_CHACHA20_POLY1305\x10\x03*\x92\x01\n" +
	"\x1eWelcomePointerWrapperAlgorithm\x121\n" +
	"-WELCOME_POINTER_WRAPPER_ALGORITHM_UNSPECIFIED\x10\x00\x12=\n" +
	"9WELCOME_POINTER_WRAPPER_ALGORITHM_XWING_MLKEM_768_DRAFT_6\x10\x02B\xf3\x01\n" +
	"\x1dcom.xmtp.mls.message_contentsB\x13WelcomePointerProtoP\x01Z;github.com/xmtp/xmtp-node-go/pkg/proto/mls/message_contents\xa2\x02\x03XMM\xaa\x02\x18Xmtp.Mls.MessageContents\xca\x02\x18Xmtp\\Mls\\MessageContents\xe2\x02$Xmtp\\Mls\\MessageContents\\GPBMetadata\xea\x02\x1aXmtp::Mls::MessageContentsb\x06proto3"

var (
	file_mls_message_contents_welcome_pointer_proto_rawDescOnce sync.Once
	file_mls_message_contents_welcome_pointer_proto_rawDescData []byte
)

func file_mls_message_contents_welcome_pointer_proto_rawDescGZIP() []byte {
	file_mls_message_contents_welcome_pointer_proto_rawDescOnce.Do(func() {
		file_mls_message_contents_welcome_pointer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_message_contents_welcome_pointer_proto_rawDesc), len(file_mls_message_contents_welcome_pointer_proto_rawDesc)))
	})
	return file_mls_message_contents_welcome_pointer_proto_rawDescData
}

var file_mls_message_contents_welcome_pointer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mls_message_contents_welcome_pointer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mls_message_contents_welcome_pointer_proto_goTypes = []any{
	(WelcomePointeeEncryptionAeadType)(0),              // 0: xmtp.mls.message_contents.WelcomePointeeEncryptionAeadType
	(WelcomePointerWrapperAlgorithm)(0),                // 1: xmtp.mls.message_contents.WelcomePointerWrapperAlgorithm
	(*WelcomePointer)(nil),                             // 2: xmtp.mls.message_contents.WelcomePointer
	(*WelcomePointeeEncryptionAeadTypesExtension)(nil), // 3: xmtp.mls.message_contents.WelcomePointeeEncryptionAeadTypesExtension
	(*WelcomePointer_V1)(nil),                          // 4: xmtp.mls.message_contents.WelcomePointer.V1
}
var file_mls_message_contents_welcome_pointer_proto_depIdxs = []int32{
	4, // 0: xmtp.mls.message_contents.WelcomePointer.v1:type_name -> xmtp.mls.message_contents.WelcomePointer.V1
	0, // 1: xmtp.mls.message_contents.WelcomePointeeEncryptionAeadTypesExtension.supported_aead_types:type_name -> xmtp.mls.message_contents.WelcomePointeeEncryptionAeadType
	0, // 2: xmtp.mls.message_contents.WelcomePointer.V1.aead_type:type_name -> xmtp.mls.message_contents.WelcomePointeeEncryptionAeadType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_mls_message_contents_welcome_pointer_proto_init() }
func file_mls_message_contents_welcome_pointer_proto_init() {
	if File_mls_message_contents_welcome_pointer_proto != nil {
		return
	}
	file_mls_message_contents_welcome_pointer_proto_msgTypes[0].OneofWrappers = []any{
		(*WelcomePointer_V1_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_message_contents_welcome_pointer_proto_rawDesc), len(file_mls_message_contents_welcome_pointer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mls_message_contents_welcome_pointer_proto_goTypes,
		DependencyIndexes: file_mls_message_contents_welcome_pointer_proto_depIdxs,
		EnumInfos:         file_mls_message_contents_welcome_pointer_proto_enumTypes,
		MessageInfos:      file_mls_message_contents_welcome_pointer_proto_msgTypes,
	}.Build()
	File_mls_message_contents_welcome_pointer_proto = out.File
	file_mls_message_contents_welcome_pointer_proto_goTypes = nil
	file_mls_message_contents_welcome_pointer_proto_depIdxs = nil
}
