// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: migration/api/v1/migration.proto

/*
Package apiv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package apiv1

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_D14NMigrationApi_FetchD14NCutover_0(ctx context.Context, marshaler runtime.Marshaler, client D14NMigrationApiClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.FetchD14NCutover(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_D14NMigrationApi_FetchD14NCutover_0(ctx context.Context, marshaler runtime.Marshaler, server D14NMigrationApiServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq emptypb.Empty
	var metadata runtime.ServerMetadata

	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.FetchD14NCutover(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterD14NMigrationApiHandlerServer registers the http handlers for service D14NMigrationApi to "mux".
// UnaryRPC     :call D14NMigrationApiServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterD14NMigrationApiHandlerFromEndpoint instead.
func RegisterD14NMigrationApiHandlerServer(ctx context.Context, mux *runtime.ServeMux, server D14NMigrationApiServer) error {

	mux.Handle("POST", pattern_D14NMigrationApi_FetchD14NCutover_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/xmtp.migration.api.v1.D14NMigrationApi/FetchD14NCutover", runtime.WithHTTPPathPattern("/mls/v2/payer/fetch-d14n-cutover"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_D14NMigrationApi_FetchD14NCutover_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_D14NMigrationApi_FetchD14NCutover_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterD14NMigrationApiHandlerFromEndpoint is same as RegisterD14NMigrationApiHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterD14NMigrationApiHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterD14NMigrationApiHandler(ctx, mux, conn)
}

// RegisterD14NMigrationApiHandler registers the http handlers for service D14NMigrationApi to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterD14NMigrationApiHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterD14NMigrationApiHandlerClient(ctx, mux, NewD14NMigrationApiClient(conn))
}

// RegisterD14NMigrationApiHandlerClient registers the http handlers for service D14NMigrationApi
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "D14NMigrationApiClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "D14NMigrationApiClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "D14NMigrationApiClient" to call the correct interceptors.
func RegisterD14NMigrationApiHandlerClient(ctx context.Context, mux *runtime.ServeMux, client D14NMigrationApiClient) error {

	mux.Handle("POST", pattern_D14NMigrationApi_FetchD14NCutover_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/xmtp.migration.api.v1.D14NMigrationApi/FetchD14NCutover", runtime.WithHTTPPathPattern("/mls/v2/payer/fetch-d14n-cutover"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_D14NMigrationApi_FetchD14NCutover_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_D14NMigrationApi_FetchD14NCutover_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_D14NMigrationApi_FetchD14NCutover_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3}, []string{"mls", "v2", "payer", "fetch-d14n-cutover"}, ""))
)

var (
	forward_D14NMigrationApi_FetchD14NCutover_0 = runtime.ForwardResponseMessage
)
