#!/usr/bin/env sh
set -e

DOCKER_IMAGE_TAG="${DOCKER_IMAGE_TAG:-dev}"
DOCKER_IMAGE_NAME="${DOCKER_IMAGE_NAME:-ghcr.io/xmtp/xmtp-prune-mls}"
GIT_COMMIT="$(git describe HEAD --tags --long)"
GO_VERSION="$(go list -f "{{.GoVersion}}" -m)"

docker buildx build \
    --tag "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}" \
    --build-arg="GO_VERSION=${GO_VERSION}" \
    --build-arg="GIT_COMMIT=${GIT_COMMIT}" \
    -f dev/docker/Dockerfile-prune \
    .
