services:
  message-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
    ports:
      - 15432:5432
  authz-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
    ports:
      - 6543:5432
  mls-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp
    ports:
      - 7654:5432

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
