# BUILD IMAGE --------------------------------------------------------
ARG GO_VERSION=unknown
FROM golang:${GO_VERSION}-alpine AS builder

# Get build tools and required header files
RUN apk add --no-cache build-base

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -tags="gowaku_no_rln" -ldflags="-X 'main.Commit=$GIT_COMMIT'" -o bin/xmtpd-prune cmd/prune/main.go

# ACTUAL IMAGE -------------------------------------------------------

FROM alpine:3.12

ARG GIT_COMMIT=unknown

LABEL maintainer="eng@ephemerahq.com"
LABEL source="https://github.com/xmtp/xmtp-node-go"
LABEL description="XMTPD Prune MLS"
LABEL commit=$GIT_COMMIT

# color, nocolor, json
ENV GOLOG_LOG_FMT=nocolor

COPY --from=builder /app/bin/xmtpd-prune /usr/bin/

ENTRYPOINT ["/usr/bin/xmtpd-prune"]
